<a href="https://colab.research.google.com/github/Masakinka/python_for_ds_task/blob/main/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
# Генерація випадкових чисел з модулем random.uniform
vector_uniform = np.random.uniform(0, 1, 10)

# Або створення вектора з допомогою методу numpy np.random.rand
vector_rand = np.random.rand(10)

# Виведення на екран вектора
print("Вектор (random.uniform):", vector_uniform)
print("Вектор (np.random.rand):", vector_rand)

Вектор (random.uniform): [0.65404692 0.41106765 0.98834777 0.58924389 0.62509414 0.6736042
 0.09740197 0.64526386 0.37314704 0.88962097]
Вектор (np.random.rand): [0.64487019 0.58315785 0.62012293 0.49363822 0.15850394 0.38065471
 0.60810668 0.60458536 0.57323526 0.71291622]


In [3]:
# Створення матриці типу numpy.array
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

# Виведення на екран матриці
print("Матриця:")
print(matrix)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [4]:
# Розмір вектора
print("Розмір вектора:", vector_uniform.shape)

# Розмір матриці
print("Розмір матриці:", matrix.shape)

Розмір вектора: (10,)
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [16]:
# Генерація випадкових чисел для вектора
vector = np.random.uniform(0, 1, 10)
print("Оригінальний вектор:", vector)

# Додавання 10 і округлення до 2 знаків після коми
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор після додавання 10 і округлення:", vector_plus_10)

Оригінальний вектор: [0.46796251 0.79652941 0.05984335 0.30154965 0.79260242 0.74228641
 0.35811587 0.48224125 0.28075639 0.15236592]
Вектор після додавання 10 і округлення: [10.47 10.8  10.06 10.3  10.79 10.74 10.36 10.48 10.28 10.15]


In [17]:
# Помноження кожного елемента матриці на 2
matrix_times_2 = matrix * 2
print("Матриця після множення на 2:")
print(matrix_times_2)

Матриця після множення на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 1х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [33]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [32]:
# Множення матриць A і B
result_matrix = np.dot(B, A)
print("Результуюча матриця після множення A і B:")
print(result_matrix)

Результуюча матриця після множення A і B:
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [34]:
# Задання вектора C (коректний розмір для множення) // бо розмірність result_matrix 3х3, а С 1х2 і буде помилка
# C = np.array([[1], [0], [1]])

# Множення result_matrix на вектор C
result_vector = np.dot(result_matrix, C)
print("Результат множення result_matrix на вектор C:")
print(result_vector)

Результат множення result_matrix на вектор C:
[[0.5202]
 [0.2846]]


In [35]:
# Множення result_matrix на матрицю D
# Для цього потрібно змінити розміри матриць
# result_matrix_2x2 = result_matrix[:2, :2]
final_result = np.dot(result_matrix, D)
print("Результат множення result_matrix на матрицю D:")
print(final_result)

Результат множення result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [36]:
# Транспонування result_matrix
result_matrix_T = np.transpose(result_matrix)
print("Транспонована result_matrix:")
print(result_matrix_T)
print("Форма транспонованої result_matrix:", result_matrix_T.shape)

Транспонована result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]
Форма транспонованої result_matrix: (2, 2)


In [37]:
# Створення вектора для прикладу
vector = np.random.uniform(0, 1, 10)
print("\nОригінальний вектор:")
print(vector)


Оригінальний вектор:
[0.93935691 0.89475148 0.10165221 0.35630782 0.52530145 0.32290528
 0.24567221 0.07535754 0.11001071 0.28564796]


In [38]:
# Транспонування вектора
vector_T = np.transpose(vector)
print("\nТранспонований вектор:")
print(vector_T)
print("Форма транспонованого вектора:", vector_T.shape)


Транспонований вектор:
[0.93935691 0.89475148 0.10165221 0.35630782 0.52530145 0.32290528
 0.24567221 0.07535754 0.11001071 0.28564796]
Форма транспонованого вектора: (10,)


In [39]:
# Використання numpy.expand_dims над вектором vector з аргументом axis=1
column_vector = np.expand_dims(vector, axis=1)
print("\nВектор після expand_dims (column_vector):")
print(column_vector)
print("Форма column_vector:", column_vector.shape)


Вектор після expand_dims (column_vector):
[[0.93935691]
 [0.89475148]
 [0.10165221]
 [0.35630782]
 [0.52530145]
 [0.32290528]
 [0.24567221]
 [0.07535754]
 [0.11001071]
 [0.28564796]]
Форма column_vector: (10, 1)


In [40]:
# Транспонування column_vector
column_vector_T = np.transpose(column_vector)
print("\nТранспонований column_vector:")
print(column_vector_T)
print("Форма транспонованого column_vector:", column_vector_T.shape)


Транспонований column_vector:
[[0.93935691 0.89475148 0.10165221 0.35630782 0.52530145 0.32290528
  0.24567221 0.07535754 0.11001071 0.28564796]]
Форма транспонованого column_vector: (1, 10)
