<a href="https://colab.research.google.com/github/Masakinka/python_for_ds_task/blob/main/HW_%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BB%D0%BE%D0%B3%D1%96%D1%81%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%97_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%96%D1%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Вхідні дані
z = np.array([-2, -1, 0, 1, 2])

# Обчислення сигмоїди для заданих значень
sigmoid_values = sigmoid(z)
sigmoid_values

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [3]:
def hypothesis(theta, X):
    # Обчислення theta транспоноване помножене на X
    z = np.dot(X, theta)
    return sigmoid(z)

# Параметри моделі
theta = np.array([0.5, -0.5])

# Дані (матриця признаків)
X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])

# Обчислення значень гіпотези для заданих даних
hypothesis_values = hypothesis(theta, X)
hypothesis_values

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [4]:
def compute_gradient(theta, X, y):
    m = len(y)  # Кількість тренувальних прикладів
    predictions = hypothesis(theta, X)
    errors = predictions - y
     # Обчислення градієнта: середнє з добутків помилок та признаків
    gradient = np.dot(X.T, errors) / m
    return gradient

# Вектор цільових значень
y = np.array([1, 0, 1, 0])

# Обчислення значень функції градієнтів
gradient_values = compute_gradient(theta, X, y)
gradient_values

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    m, n = X.shape  # Кількість тренувальних прикладів та признаків
    theta = np.zeros(n)  # Ініціалізація параметрів моделі

    for _ in range(epochs):
        predictions = sigmoid(np.dot(X, theta))
        errors = predictions - y
        gradient = np.dot(X.T, errors) / m
        theta -= lr * gradient  # Оновлення параметрів

    return theta

# Виклик функції градієнтного спуску
theta_final = full_batch_gradient_descent(X, y)
theta_final

array([-0.2893693 ,  0.77655125])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [11]:
def predict_proba(theta, X):
    """Розрахунок імовірності належності прикладу до класу 1."""
    return sigmoid(np.dot(X, theta))

def predict(theta, X, threshold=0.5):
    """Передбачення класу на основі визначеного порога."""
    probabilities = predict_proba(theta, X)
    return (probabilities >= threshold).astype(int)

def accuracy(y_true, y_pred):
    """Обчислення точності моделі."""
    return np.mean(y_true == y_pred)

# Обчислення імовірностей, класів та точності моделі
probabilities = predict_proba(theta_final, X)
predictions = predict(theta_final, X)
model_accuracy = accuracy(y, predictions)

#probabilities, predictions, model_accuracy

# Вивід результатів
print("Імовірності належності до класу 1 для кожного прикладу:")
for idx, prob in enumerate(probabilities, 1):
    print(f"X{idx}: {prob:.4f}")

print("\nПередбачені класи для кожного прикладу:")
for idx, pred in enumerate(predictions, 1):
    print(f"X{idx}: {pred}")

print(f"Точність моделі: {model_accuracy:.0%}")

Імовірності належності до класу 1 для кожного прикладу:
X1: 0.7797
X2: 0.2562
X3: 0.4282
X4: 0.6194

Передбачені класи для кожного прикладу:
X1: 1
X2: 0
X3: 0
X4: 1
Точність моделі: 50%
